Mapper Thread: -1
Feature Detection Thread: -1
Pull LI IMU Thread: -1
Image Stream Thread: -1
Multiframe Consumer Thread: -1
Drawing Thread: -1
Matching Thread: -1
Optimization Thread: -1
IMU Consumer Thread: -1
Heartbeat Detector Thread: -1
Publisher Thread: -1
Visualization Thread: -1
VizReprojection Thread: -1