%YAML:1.0
rgb_scale: 2
ir_scale: 2
use_orig_sgbm: 1
sgbm_min_disp: 0
sgbm_num_disp: 48
sgbm_block_size: 9
sgbm_p1: 120
sgbm_p2: 2000
sgbm_disp12_maxdiff: 1
sgbm_unqiue_ratio: 8
# sgbm_descriptor_type: 2
sgbm_blank_range: 12

refine: 1
use_confidence: 1
wls_lambda: 2000
wls_sigma: 0.2